### ISSUE TITLE
cecdaemon operating on incorrect HDMI input #

### ISSUE THREAD

**Issue by aanderse** [simons-public/cecdaemon#1]
I tried this software when my TV was plugged into HDMI input #4 and nothing happened. When I switched the TVs input to HDMI input #1 the software worked. There was nothing plugged into HDMI input #1 on my TV.

**Comment by simons-public** [comment]
Thanks for the issue report, can you elaborate on what didn't work? If it was the remote did you select the device in your CEC control menu? For example, when I use my Sony TV I have to go to the Bravia Sync menu and select the device for remote to pass through. Also, did the name in the configuration display on the tv? If you could post the output of running it with the '--debug' argument that might help me narrow it down too. Thanks

**Comment by aanderse** [comment]
Normally Kodi manages CEC on that computer but I specifically disabled that so your software could manage it. The computer is plugged into HDMI input #4 on the TV and this works with Kodi, but when your software was running nothing was working on HDMI input #4 (no input detected). I switched through the different HDMI inputs and on input #1 your software register input.

**Comment by simons-public** [comment]
Ok, since you mentioned input I assume you were talking about the remote input so I went back to the CEC Specifications document and did some reading. I think I may have fixed this issue by sending the CEC opcode that lets the tv know there's a menu and it's wanting user control input. Please let me know if this fixes the issue for you, thanks.

**Comment by aanderse** [comment]
Sorry i never ended up getting around to testing this as I found a more relevant solution.
